### ISSUE TITLE
Bertram's own TODO-list

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#1]
**General:**
- [x] Import issues in the issue tracker

Once the move to github is all and well:
- [x] Fix the repository links in the readme.
- [x] Check the wiki and update the compile instructions/FAQ and such...

**Models:**
- [x] Add new gold bags.
- [x] Add golem and beetle monster.
- [x] Add support for a basic hatchery room.

**Creatures:**
- [x] Make the creature action list be cleared when dropped somewhere, so they don't simply go back to their previous action when dropped in front of enemies or new tiles.
- [x] Check what small piece of improvement can already be added simply to creatures:
  - [x] First things first, make creatures react directly to enemy ones, not only as a chance.
  - [x] Make worker flee more easily than fighters since it is what is expected.
- [x] Have a try at making workers search for available/reachable marked tiles when idling, and no visible marked tiles. This might include seeking why creatures has troubles going through narrow (1-tile wide) passages when not dropped in front of them.
- [x] Once this kind of logic works for marked tiles, claiming ground and wall tiles should get the same improvement.

**Graphics:**
- [x] Add the CEGUI skin support for in game windows, and maybe main controls.
- [x] Fix the glitch seen when a worker half-claim a tile, making it of the team color but not claimed. The tile should then remain untainted.
- [x] Ask on Ogre how to work on the RT Shader system/normal maps, and materials and speak about the problems seen on OD. (Seen also with oln.) http://forum.freegamedev.net/viewtopic.php?p=58119#p58119
- [x] Have a look at the `ERROR: Unhandled render request` debug statement and fix its causes if possible.
- [x] Fix the material script errors seen on logs.

**Nest tasks:**
- [x] Work on the tileset.cfg file specs and code to fix current tiling problems, and add preliminary biomes support.
- [x] Start adding rooms conditions, simplest first, and support to only show a room button when it is meeting the conditions.

**Comment by Bertram25** [comment]
Issue obsoleted by all the improvements done.
I've got other issues to know what to do now.
