### ISSUE TITLE
0.6.0 Release

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#540]
Here we go!! :D 

**General**
- [x] Allow to display callstack when a crash occurs with MSVS2013 versions #701 
- [x] Homogenize how the callstack is displayed independently from platform (to avoid using platform specific flags everywhere in the code) #701 
- [x] RectLayoutManager - is it used for anything? #690 
- [x] The training room max training level should be part of room config #698 
- [x] Move the game binary version to 0.6.0 #731 
- [x] Refactor a bit how modes are handled. #670 
- [x] Command-line options #688 
- [x] Dedicated server support. #665 
- [x] Add a cheat to unlock all skills at once #729 
- [x] Creature gold handling vs Payday #704 
- [x] Research manager to gather some glue code more properly. #843 
- [x] Build failure on MingW64 system due to bad CEGUI::getProperty() call. #889 

**Gameplay**
- [x] Add heal and explosion spells #706  
- [x] Add haste spell #842 
- [x] Improve spell logic - Done: #683 #727 #710 #741  
- [x] Reworked library logic #817
- [x] Add a warning when a player adds a trap but doesn't own a workshop (yet or anymore.) #671 
- [x] Tell about payday if at least one fighter and an active temple. #715 
- [x] Easy to sacrifice the creature when placing it #722 
- [x] Research queue handling improvement #851 

**Levels**
- [x] Remove levels redundancy #696 
- [x] Improve the Bridge level #673 
- [x] Drop the intermediate tile fullness values in the editor #590 
- [x] New Level! #847 

**Graphics**
- [x] Better-looking claimed walls models #808 #818
- [x] Add support for particle effects on entities. Done: #683 #709 #710 #711  
- [x] Add a position offset to creature position when there are more than one on the same tile. #697
- [x] Make goldbags have random orientation and offsets. #725
- [x] Scarab nose too thin #721 
- [x] Make most interesting models use normal maps. #511
- [x] Fix default tileset glitches Done: #273 #694 

**UI**
- [x] Key to hide keeper hand and tile selector #684 
- [x] Texts overlay handling improvement. #713 
- [x] Make a better distinction between names of game UI tabs and configuration menus #703 
- [x] Check whether there is a way to make the in-game buttons more responsive #343 
- [x] Skull flags - Improvement - Creature health and states. #733  #734
- [x] Add an in-game option + settings menu #3 
- [x] Research dependency + custom order handling #577 
- [x] Research button improvement. #840 
- [x] GUI: Visually show the cooldown on spells buttons #858
- [x]  Notify player when the research queue is empty #869 
- [x]  Spell button refinements #882 #883 
- [x]  Show human readable spell name next to the tile selector instead of code name #863 
- [x] Research button refinements #894 

**Sounds**
- [x] Menus music should be dehardcoded #632 
- [x] Sounds per creature classes and actions support #126 

**Documentation**
- [x] Document the creation of models with normal support.
- [x] Document the creation of models with transparency support.
- [x] Document Creatures and Rooms per Tiers in the wiki #705 
- [x] Announcement #845 #846  
- [x] Review quick help for 0.6.0 #890 

---
- [x] Have a good lan to test multiplayer + save MP games.
- [x] Review the CREDITS file for potential mistakes.
- [x] [CodeSpell](https://github.com/lucasdemarchi/codespell) the code.
- [x] Review a bit the wiki overall content.
- [x] And of course, release once all that is done. ;)

**Comment by Bertram25** [comment]
Once the release news is out, it'll be time to open a new discussion thread on OD forums for 0.6.0 :D 
It will be two releases done!

**Comment by Danimal696** [comment]
Not much to fill out on this one, yet...

**Comment by akien-mga** [comment]
Yeah, we'd better discuss this all on the forum to maybe also get feedback from players directly, and determine our roadmap for 0.6.0.

**Comment by Bertram25** [comment]
> Yeah, we'd better discuss this all on the forum to maybe also get feedback from players directly, and determine our roadmap for 0.6.0.

Yeah, it's time to open a new topic about what we want for 0.6.0. If I could just release the win32 binary with all the deps before next month... XD

**Comment by Danimal696** [comment]
when will you open it? i have a few ideas

**Comment by Bertram25** [comment]
> when will you open it? i have a few ideas

Sure:
http://forum.freegamedev.net/viewtopic.php?f=35&t=6299

**Comment by Bertram25** [comment]
pinging also @oyvindln @Wout-van-Dongen @hwoarangmy @eugeneloza 
Hey,
I've updated the 0.6.0 issue content to reflect the current effort. :)

This one is big and will be quite a good stuff to release.
I'll also add an issue about the fact that the development branch game should now be 0.6.0 as there already are incompatible level changes.

Let's review the progress and iteration drifting in a month. :D 

In the meanwhile, if you see anything to change, comment and so on. Feel free to do so. :)

**Comment by hwoarangmy** [comment]
There are more here than what I was expecting ^^
Let's try to do most of it.

**Comment by Bertram25** [comment]
Don't worry, we'll likely move the hurting pieces preventing from releasing as we want once we're at mid scope.

**Comment by Bertram25** [comment]
@akien-mga @hwoarangmy @Danimal696  Just for the small point of situation. What are your current short-term mid-term plan?
Mine is to:
- [x] Finish support for custom settings.
- [x] Made sound volume change heard immediately.
- [x] Made all the video renderer options listed in the settings automatically.
- [x] Move settings to full custom settings.

**Comment by Danimal696** [comment]
unless last minute change:
- Fix current tileset, the dungeon biome; gold texture not tiling, gem blocks, lava/water rotation.
- Stone bridge model
- New cannon model

**Comment by hwoarangmy** [comment]
- Implement new decided library logic
- Improve ranged creatures fighting behaviour

**Comment by akien-mga** [comment]
My current list:
- Finish moving away from SF.net to tuxfamily.org for file hosting and nuke the SF repo :)
- Fix links everywhere (README, wiki, website)
- Create a couple skirmish maps :)
- Code-wise, I might try to have a go at loading user content from mUserPath

**Comment by eugeneloza** [comment]
A quick note: tuxfamily.org does _not_ support CC-BY license (including OGA-BY), only CC-BY-SA. See: http://faq.tuxfamily.org/License/En . They have no statement about CC0, but it seems to be ok for them.
It should be checked before moving to this hosting. Or contact them on IRC to re-check if they demand this deliberately or it's just a poorly written document 'cause GNU license guide they referr to supports CC-BY.

**Comment by akien-mga** [comment]
> A quick note: tuxfamily.org does not support CC-BY license (including OGA-BY), only CC-BY-SA. See: http://faq.tuxfamily.org/License/En . 

They say "We do accept other open licenses, feel free to join our irc channel if you have questions about a specific license." I think it's just a badly written document, as I don't see why they would accept GPL and BSD code (i.e. strong copyleft and almost public domain) but not CC-BY for artwork. I'm asking them on IRC to clarify.

_Edit:_ Confirmed on IRC, they accept any CC license as long as it's not NC or ND, which seems pretty classic to me. As I understand it, the licenses that they list are recommendations for projects _without_ license, but not strong enforcements for already licensed projects.

**Comment by Bertram25** [comment]
Perfect. Thanks for the heads up. :)

**Comment by hwoarangmy** [comment]
Note that we are already at 4 months from the start of 0.6.0 dev. Should we start moving to next version what won't be done in a near futur ?

**Comment by Bertram25** [comment]
> Should we start moving to next version what won't be done in a near futur ?

I'm not sure I get what you mean, sorry.

**Comment by Bertram25** [comment]
ah I took what for that.

**Comment by Bertram25** [comment]
@hwoarangmy 

> Should we start moving to next version what won't be done in a near futur ?

What have you got in mind? Or more precisely what do you think should be moved?

**Comment by Bertram25** [comment]
I would also add that we should all have a look at all the issues open and see whether there are points not clear about how to fix the issues. We never know, we may even have forgotten a few ones to close? ;)

**Comment by hwoarangmy** [comment]
> What have you got in mind?

ATM, I've released a PR with library logic (obviously what I was on). So I guess we should move all non "critic" stuff to later and focus on what we are currently doing or what we really want for the 0.6.0. For my part, I've nothing to do unless you see something in my PR ^^

**Comment by Bertram25** [comment]
> on what we are currently doing or what we really want for the 0.6.0.

Good for me. I'm always for smaller and saner scopes. ;)
I'd like to see #590 #632 fixed as such details can be removed from the way once and for all, and #722 for usability purpose.
(I'm fixing the settings as requested atm.)
All the rest can move to 0.7 or 0.6.1 as you like, where I'll personally keep on with the GUI stuff. (bugs, skin + help @akien-mga with user maps support.)
Why not focus on equipment for the next release, while @Danimal696 keeps on fixing the tileset?

**Comment by Bertram25** [comment]
Ah, while we're speaking of that kind of stuff. There is a bit of vision to discuss:
For the next release or the one after that, shall we:
1. Keep focusing on adding missing rooms, and such?
2. Have a look at the master server implementation and try to have a good base of wan multplayer games?
3. Start looking at scripting toward campaign support?

My own preference is the given order. Why? Because we still need a few stuff to complete the gameplay, such as gems, bridges, a room or two and a few more spells, but we are also mostly known to be multiplayer stable and permitting to let people join a masterserver could really help the project to be even better at that, before we move onto a completely different subject (The campaign)
WDYT?

**Comment by hwoarangmy** [comment]
IMHO, the most missing right now is game content. ATM, the game is too repetitive. Building a hatchery + dormitory is enough to unlock almost everything. I think we should go for 2-3 specific rooms and a few spells to make the game fun ^^
Concerning points 2 and 3, I would also choose the same order because IMHO, the point of the whole project is to have a multiplayer game (otherwise, playing DK2 would be enough).

**Comment by Bertram25** [comment]
We're in line then. :)

**Comment by Bertram25** [comment]
@OpenDungeons/developers 
As we're in what could be called "integration" phase for 0.6.0, I'd propose this:
- Move sounds part to 0.7 (Sorry again @eugeneloza :S) 
- Move the user map support part to 0.7 as well (IMHO, it goes along with creating a new map from the editor for usability purpose). Let's let @akien-mga and me kill that for 0.7
- Move the forge and equipment system to 0.7 (It will be the shiny new feature of it, I guess?)
- Move the small GUI glitches to 0.7 as well (Because I need time to investigate, maybe ask on forums, ...) + tab support seems not that easy to add or to be done case per case. I need to investigate that, too.

On the other hand, it would be a cool milestone if we could fix the tileset before that release, and I'd like to keep documentation to fix here, to make it happen before we move onto next topics.
EDIT: Ah, And I'll try to make the skill button happen asap while I still have no eta.

WDYT?

**Comment by akien-mga** [comment]
First of all, I agree with the general vision outlines above (more game content first, then masterserver, then campaign).

For the 0.6.0 integration phase, I also agree with @Bertram25's points. I'll create issues for the remaining points that I want to fix before the release (create a new map, finish the move to TuxFamily, update the release notes).

As we're still working on core gameplay elements, I guess the level format will continue to evolve, so our next release will probably be a 0.7.0 and not a 0.6.1. If you agree, let's create the 0.7.0 milestone and start moving stuff to it.

**Comment by Bertram25** [comment]
> As we're still working on core gameplay elements, I guess the level format will continue to evolve, so our next release will probably be a 0.7.0 and not a 0.6.1. If you agree, let's create the 0.7.0 milestone and start moving stuff to it.

Sure, I'll create the milestone now. :)
Edit: Done: https://github.com/OpenDungeons/OpenDungeons/milestones/0.7.0

**Comment by Danimal696** [comment]
> And I'll try to make the skill button happen asap while I still have no eta.

I havent heard about that, what is it about?

**Comment by hwoarangmy** [comment]
That's the button that displays a progressbar for researches

**Comment by Bertram25** [comment]
@Danimal696 @hwoarangmy Ok with my move proposal?

**Comment by Danimal696** [comment]
yes, go ahead

**Comment by Bertram25** [comment]
3 voices. Ok. I apply.

**Comment by hwoarangmy** [comment]
> Ok with my move proposal?

It sounded like a summary, I didn't get that you were waiting an approvation ^^
But as I said, I am for finishing what we all are doing and releasing ASAP. IMO, the only "blocking" issue would be the water/lava animation (even if it is a big problem in my mind)

**Comment by Bertram25** [comment]
@hwoarangmy Eh eh. Did I sound that much like a dictator? XD 
There are at least one task left for each of us so hopefully you'll have a bit more time to finish what you will. :)

**Comment by Danimal696** [comment]
hwoarangmy i posted the models into the forum in case you didnt see my topic reply

**Comment by Bertram25** [comment]
@akien-mga Thanks for the wiki cleanups. We're mostly done on the communication part now. :)

**Comment by alketii** [comment]
For 7.0 release, please add Masterserver.

**Comment by Bertram25** [comment]
> For 7.0 release, please add Masterserver.

I'll add it. Let's pray that someone bites it during that release. ;)

**Comment by akien-mga** [comment]
> For 7.0 release, please add Masterserver.

You don't like our leading 0, do you? :p
I think **0.**7.0 is important to show that we are well aware that our game is not complete yet :)

**Comment by Bertram25** [comment]
We're getting close! :)

**Comment by alketii** [comment]
great news

**Comment by hwoarangmy** [comment]
I will upload a PR tonight with the last needed fixes. Once it will be reviewed/merged, the RC1 will be on its way ^^

**Comment by akien-mga** [comment]
> I will upload a PR tonight with the last needed fixes. Once it will be reviewed/merged, the RC1 will be on its way ^^

Nice :) So once this PR is merged, I propose that we create the 0.6 branch from the development one, and use it as a basis for RC1. IMO we don't need to add a git tag for RC1, I think all our testers will use the precompiled binaries, and we don't really need to keep a tagged RC1 for the posterity (I'd even remove the existing 0.4.9-RC1 and 0.5.0-RC1 tags, but that's nit-picking, they don't hurt :p).

**Comment by Bertram25** [comment]
Left is adding the announcement and maybe a few balancing tweaks. RC1 is good to go before lans! :D

**Comment by Bertram25** [comment]
Sound and balancing tweaks in. Announcement draft done!

**Comment by akien-mga** [comment]
Nice! I think it's time to branch development into a new 0.6 branch, and that we create the RC1 binaries for wider testing. I'll do the Linux binaries in the evening or tomorrow.

**Comment by Bertram25** [comment]
> Nice! I think it's time to branch development into a new 0.6 branch, and that we create the RC1 binaries for wider testing. I'll do the Linux binaries in the evening or tomorrow.

Ok, will do asap. Note that you guys have the access level to do it, in case you're tempted.

**Comment by akien-mga** [comment]
@Bertram25 We're going to play test 0.6.0 RC1 with @hwoarangmy tonight, if you're around ;)

**Comment by akien-mga** [comment]
FYI, I've pushed the 0.6 branch which is currently in sync with the development one. So we can start merging 0.7 stuff in development if you want ;)

**Comment by hwoarangmy** [comment]
@Bertram25 @akien-mga Could one of you try to launch a game with valgrind to check if we have memory problems ? I don't have a Linux computer to try but I think it would be good.
The game will probably be (very) slow but if you could just open a level, let it play for some time and exit to check if everything goes well, it would be nice ^^

**Comment by Bertram25** [comment]
Sure. I'm trying to sort a few things out first, but I'll do it tomorrow evening at most. :)

**Comment by hwoarangmy** [comment]
Well, there is no rush. IMHO, it is better to wait the final release candidate

**Comment by Bertram25** [comment]
> Well, there is no rush. IMHO, it is better to wait the final release candidate

My thought as well. It seems there are still a few vital bits waiting. Thanks for the branch, though. :)

**Comment by akien-mga** [comment]
FYI: I moved to Germany yesterday and started a new job, and I don't have flatrate Internet at home yet, so I might be less active than I used to in the coming weeks. I can still reroute my phone's data to the laptop, so I won't be totally off ;-)

**Comment by akien-mga** [comment]
@Bertram25 I built RC2 binaries locally, but I don't have flatrate Internet at home and don't want to kill my work phone data quota by uploading a 100 MB tarball ;-)
If you want to have a look at making Linux binaries yourself, feel free to do it. Another simpler alternative would be that I send you only the binary + bundled libraries (8 MB compressed), and you could generate the tarball with data yourself.

Or we're not in a hurry and I'll upload my tarball next time I go to McDonald's to use their free Wi-Fi ;)

**Comment by akien-mga** [comment]
BTW I think I need to update the linux build scripts in the repo, I've reworked them a bit IIRC.

**Comment by akien-mga** [comment]
I just went through the open issues, we do a pretty good bug triage work IMO, everything is well categorised. I'm eager to get started with 0.7.0, let's get this 0.6.0 out soon :-D

**Comment by akien-mga** [comment]
@OpenDungeons/developers He's everywhere!
![imag0049](https://cloud.githubusercontent.com/assets/4701338/9563752/cc6adc32-4e8e-11e5-86f3-8213dae56cac.jpg)

**Comment by Bertram25** [comment]
:D Thanks for the pic!

**Comment by Danimal696** [comment]
My god, a street named after him! He´s hiding something from us all!

By the way, what is stoping the 0.6.0 release?

**Comment by hwoarangmy** [comment]
Note that we should add #935 to the 0.6.0 since we added scrollpanes in the settings menu.

**Comment by hwoarangmy** [comment]
We have a game tonight with @akien-mga and infrared. We have seen small stuff but no release blocker. Seems like 0.6.0 RC3 is the official 0.6.0 release ^^

**Comment by akien-mga** [comment]
Here it is: https://github.com/OpenDungeons/OpenDungeons/releases/tag/0.6.0

What's left is uploading the binaries and source tarball, as well as updating the website :)

**Comment by alketii** [comment]
Congratulations.

**Comment by eugeneloza** [comment]
Great!!!

**Comment by akien-mga** [comment]
Win32 and Linux64 binaries + the source tarball are now on the FTP.

**Comment by akien-mga** [comment]
The release announcement is posted on the website: http://opendungeons.github.io/

**Comment by akien-mga** [comment]
And posted on the forum: http://forum.freegamedev.net/viewtopic.php?f=36&t=6540
