### ISSUE TITLE
Addition of a few better sounds and musics.

### ISSUE THREAD

**Issue by Danimal696** [OpenDungeons/OpenDungeons#95]
Initially on Paul´s hands:

http://forum.freegamedev.net/viewtopic.php?f=35&t=5691
http://forum.freegamedev.net/viewtopic.php?f=39&t=5695

Basically making easier to add new music, a crossfading system between songs and adding sounds to creatures actions like walking, attacking, pain...

TODO Summary:
**Bertram**
- [x] Improved creature sound system Mk I  #94 
- [x] improved music system #23 - Done with #125 
- [x] Cross fade support #23 - Done with #125 
- [x] New battle music & Battle music triggered when there are skirmish: http://opengameart.org/content/the-dark-amulet-dark-mage-theme #23 - Done with #140 
- [x] Canon firing: http://opengameart.org/content/synthesized-explosion
- [x] Deposit coins on treasury: http://opengameart.org/content/coins-sounds
- [x] New dig select sound: http://forum.freegamedev.net/viewtopic.php?f=39&t=5695&p=59382#p59382

**Danimal696**
- [x] Optional: New default creatures pick-up sounds.
- [x] Optional: New default creatures drop sounds.

**Comment by Bertram25** [comment]
Hi,

I was more thinking you had precise examples to add in game right now in fact. ;)
This issue is very close from #23 

Would you mind if we only talk about adding more sounds here?
I was thinking about those ones that could be done right away:

Canon firing: http://opengameart.org/content/synthesized-explosion
Deposit coins on treasury: http://opengameart.org/content/coins-sounds

**Comment by hwoarangmy** [comment]
FYI : I will add in my next pull request support to play sounds on client side. This is needed especially for creatures as, like I said in another thread, on the client side, there is no dig or attack or whatever. They just move and change animation. Then, we will have to check if the other sounds are played as they should (ie on client side).

**Comment by Danimal696** [comment]
yes, ill convert a few songs and
Canon firing: http://opengameart.org/content/synthesized-explosion
Deposit coins on treasury: http://opengameart.org/content/coins-sounds

**Comment by hwoarangmy** [comment]
It's done. When the pull request will be integrated, sounds will be played on client side instead of server.

**Comment by Bertram25** [comment]
@Danimal696 Hi :)
Feel free to hint me when the sounds/music is ready, I'll have a look at integrating it, while I'm on Audio business. ;)

**Comment by Danimal696** [comment]
Sorry, later this week, when im no sleep deprived from uni exams. Do you prefer bgms over sounds or the other way round?

**Comment by Bertram25** [comment]
> Sorry, later this week, when im no sleep deprived from uni exams.

The uni exams first. :) So no OD for you until you are allowed to sleep, ok? ;)

> Do you prefer bgms over sounds or the other way round?

I guess you're speaking about ambience, such as water drops heard faraway with some reverb?
I do think we need both, but music should be music and such ambient sounds should remain sounds.
Thus we can reuse the same ambient sounds with a different music, and mix the two kinds at our discretion.

Makes me think we could use some water drops for caves, and maybe later some forest sounds for maps in a pseudo open space, or anything that pops up the modder evil mind. ;)

**Comment by Danimal696** [comment]
BGM = background music; yes i found a few of those ambience sounds, it will be nice if getting near the water triggers a water drops sounds or lava splashes; some of the rooms could have this as well, like the cementery or dark temple having an ominous soft chanting; training over dummies having a "swosh" sound...

**Comment by Bertram25** [comment]
> BGM = background music; yes i found a few of those ambience sounds, it will be nice if getting near the water triggers a water drops sounds or lava splashes; some of the rooms could have this as well, like the cementery or dark temple having an ominous soft chanting; training over dummies having a "swosh" sound...

Small length spatial sounds can be added rather easily IMHO. :) Especially now we seem to have rather correct spatial attenuation values.

As for the sounds that are looped, I don't know whether we can safely ask a spatial sound to play looped and get away with it, especially if there can be dozens of it. I do wonder whether OpenAL (the beast under SFML::Audio) does or needs to do some auto-culling about it to not clutter all the audio channels, and such.
Otherwise, we'd need to stop sounds when they are too far away by checking the vector distance for every looped sounds.

**Comment by Bertram25** [comment]
Ok, I've checked that point. We can safely add short sounds as spatials, especially as we're caching the sound to reuse buffers, but we will have stop (cull) looped sounds that are too faraway ourselves if we don't want to use too much audio memory.
N.B.: Spatial sounds must be mono-channel to work.

So in order to close this issue, I'm ok with adding the cannon and gold deposit sounds, and add a few tracks, that @Danimal696 can point at. But I'd rather put the ambient sounds for later, and in another issue.
(I'll be working on adding the default map music as a level parameter #23 for the release.)
What do you think guys?
If you're ok with it, I'll add an issue about the ambient sounds for later.

**Comment by Bertram25** [comment]
As told in the forums, a better dig select sound is also needed.

**Comment by Bertram25** [comment]
@Danimal696 I'll deal with my part of the issue (See the TODO list above) rather soon. Do you still want to choose some new dig select/default pick-up/drop sound before 0.4.9 release?

**Comment by Danimal696** [comment]
yes, at least for digging. will get to it today.

**Comment by Danimal696** [comment]
Diggind sound: http://forum.freegamedev.net/viewtopic.php?f=39&t=5695&p=59382#p59382

**Comment by Danimal696** [comment]
did you prepare new sounds for gold and cannon as well Bertram? and for pick up  and drop?

**Comment by Bertram25** [comment]
@Danimal696 I've prepared the new cannon sound, all the gold deposit sound and the new pickaxe one.

**Comment by Bertram25** [comment]
As for pick/drop. I've let the one previously given. :)

**Comment by Bertram25** [comment]
Were you planning to find some new ones for such actions?

**Comment by Danimal696** [comment]
im short on time these days, so if you did, its good. :)
